### ISSUE TITLE
Allow passing managed callbacks to native code through interop

### ISSUE THREAD

**Issue by MuffinTastic** [mocha-engine/mocha#44]
I feel it would be good to be able to make a callback on the managed side, and pass it to the native side. The primary use case for this is the console system, so that everything for actually running commands can be on the native side instead of splitting the system up in weird ways.

**Comment by MuffinTastic** [comment]
The use case I thought up for this is no longer relevant but I figure I'll leave this open in case it's still desirable

**Comment by xezno** [comment]
I'll look into this, but I can't say if it's possible / easy: the C# garbage collector likes to move things around; if we get a pointer to a C# function we can't really store it because it might be invalid the next time we want to use it

**Comment by peter-r-g** [comment]
This is resolved with #58 right?

**Comment by xezno** [comment]
Yeah I think so
